### ISSUE TITLE
Captions

### ISSUE THREAD

**Issue by KosmosisDire** [vertis/obsidian-image-layouts#11]
I have a few comments on the current captions:
- I feel a better way to approach setting a caption is to just write the caption under the link to each image. This makes defining the caption much easier. 
- It only shows one caption for the whole layout but I would like one caption per image with each caption centered on it's image. 
- The text also doesn't follow the theme, so it is invisible in dark mode.

![image](https://github.com/vertis/obsidian-image-layouts/assets/39423700/e18d0640-3c08-4355-b61a-573a9885fa61)
You can barely see the caption there at the bottom.

Here is my proposed way of setting per image captions.
I think this would also translate much better if the plugin were to be uninstalled. Because then the caption will show up as text underneath each image by default (once the codeblock is removed). Frontmatter is not human friendly

````
```image-layout-a
You could write text here for a caption of the whole layout

![[ASEE Paper - Full Render.png]]
Or caption for *first* image here.
You could even use multiple lines.
And the caption _should_ be rendered as markdown.
![[ASEE Paper - Full CAD.png]]
Caption for second image here!
```
````

**Comment by KosmosisDire** [comment]
I realize after I posted this that the overlays are meant to be per image. Maybe I can just style the overlay to look like a caption and make it show even when not hovered.

**Comment by scokobro** [comment]
Great plugin! 
For markdown-style image links - `![alt text](path/to/image)` -  it might be sensible to use the `alt text` as the overlay, this would make it similar to tools like `pandoc`.
Also. I can't get overlays/captions to work at all! Does the YAML front-matter go in the Obsidian text file or in the code block? Docs are not really clear😉

**Comment by vertis** [comment]
@scokobro yeah, that seems like something I would like in the next little while. Gotta work on the RegEx to extract the alt text :)

**Comment by vertis** [comment]
@KosmosisDire yeah, that should be a pretty easy modification to make it show all the time vs only on hover

It's in my todolist to make the CSS a lot more configurable

**Comment by vertis** [comment]
@scokobro @KosmosisDire I've just released an update that covers all these issues
- Masonry overlays and captions should now work
- Putting the `[Text](image.jpg)` in a markdown link should now cause it to be the overlay
- putting `permanentOverlay: true` in the front matter will cause it to display the overlay all the time rather than on hover.

**Comment by KosmosisDire** [comment]
Amazing, thank you!

**Comment by vertis** [comment]
Ah I still need to fix the dark mode issue

**Comment by vertis** [comment]
Dark mode issue is now fixed in 0.14.1

**Comment by scokobro** [comment]
Very impressive! That was some speedy work - many thanks!

**Comment by saipavanc** [comment]
I am sorry to add a comment here, but how are you adding caption when the image is from the local store?
```
```image-layout-a
![[Pasted image 20240419115508.png]]
![[Pasted image 20240419120314.png]]
```
```
I have tried and it just does not work.

**Comment by johnrobertcobbold** [comment]
@saipavanc: I have the same issue trying to use local images. I have read the docs multiple times but still do not understand how captions work. Great plugin though, I am loving the masonry.
